### ISSUE TITLE
Let's simplify example integrations with XcodeGen

### ISSUE THREAD

**Issue by mickael-menu** [readium/r2-testapp-swift#390]
[Swift Package Manager support](https://github.com/readium/r2-testapp-swift/issues/305) is around the corner, thanks to @stevenzeck.

With it, we will need to add more Xcode targets to show how to use them. Currently the Test App has four of them, which adds some maintenance load:

<img width="268" alt="Screenshot 2021-06-05 at 12 49 21" src="https://user-images.githubusercontent.com/58686775/120889250-79c02c80-c5fc-11eb-95ad-291758222953.png">

I think this also adds [confusion for integrators](https://github.com/readium/r2-testapp-swift/issues/388), since the project contains artifacts for a few different types of integration.

Instead, I suggest removing the Xcode project entirely from `r2-testapp-swift` and instead add one [XcodeGen](https://github.com/yonaskolb/XcodeGen) project definition YAML file per integration example.

> XcodeGen is a command line tool written in Swift that generates your Xcode project using your folder structure and a project spec. The project spec is a YAML or JSON file that defines your targets, configurations, schemes, custom build settings and many other options.

### Pros

* Xcode projects are not Git-friendly and it's frequent to have merge issues. Getting rid of it would solve the problem.
* The Xcode projects generated by XcodeGen would be simpler and a clearer example of the chosen integration type.
* XcodeGen's YAML files are human-readable and in my opinion also a better example on what's needed to integrate Readium than digging into Xcode's build settings.
    ```yaml
    name: ReadingApp
    packages:
      R2Shared:
        url: https://github.com/readium/r2-shared-swift
        from: 2.0.0
      R2Navigator:
        path: ./r2-navigator-swift-local-clone
    targets:
      ReadingApp:
        dependencies:
          - package: R2Shared
          - package: R2Navigator
    ```

### Cons

* This requires integrators to install a third-party tool.
    * Integrators can always create the project by hand following the YAML file, which should be straightforward even when not familiar with XcodeGen.
* XcodeGen might stop being maintained in the future.
    * We can always commit again the generated Xcode projects at some point.
    * There are similar alternatives.
    * This dependency is only for the test app, and not other Readium 2 modules.

### One step further

Not related to XcodeGen, but [r2-workspace-swift](https://github.com/readium/r2-workspace-swift/) also brings some maintenance load with its [4 different integration branches](https://github.com/readium/r2-workspace-swift/branches).

I suggest archiving this repository and instead adding the submodules directly in `r2-testapp-swift`, when used for development purposes.

* Simpler for onboarding, there is a single entry-point repo to check out hosting the documentation.
* It better represents the structure of an integrator's reading app, which when using submodules would have them in the app's repo.
* We can commit the submodule changes after each PR, making it much easier to pinpoint regressions using `git bisect`. Right now `r2-workspace-swift` is only updated after each release, making it not so useful.
    * EDIT: To be fair, this is something we could do in `r2-workspace-swift` too. However, having them in `r2-testapp-swift` ties any change in the Test App itself to particular commits of the R2 modules. 
* Users are free to ignore (and not checkout) the submodules when using SPM or Carthage with the test app. The only place where it would show is as empty directories on the file system.

**Comment by mickael-menu** [comment]
Example generating the test app project using SPM and with LCP:

```yaml
name: R2TestApp
options:
  bundleIdPrefix: org.readium
packages:
  R2Shared:
    url: https://github.com/readium/r2-shared-swift.git
    branch: develop
  R2Streamer:
    url: https://github.com/readium/r2-streamer-swift.git
    branch: develop
  R2Navigator:
    url: https://github.com/readium/r2-navigator-swift.git
    branch: develop
  ReadiumOPDS:
    url: https://github.com/readium/r2-opds-swift.git
    branch: develop
  ReadiumLCP:
    url: https://github.com/readium/r2-lcp-swift.git
    branch: develop
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    from: 5.15.8
  MBProgressHUD:
    url: https://github.com/jdg/MBProgressHUD.git
    from: 1.2.0
  SQLite:
    url: https://github.com/stephencelis/SQLite.swift.git
    from: 0.12.2
targets:
  R2TestApp:
    type: application
    platform: iOS
    deploymentTarget: "10.0"
    sources:
      - path: Sources
        excludes:
          - Resources/Samples
      - path: Sources/Resources/Samples
        type: folder
    dependencies:
      - carthage: R2LCPClient
      - package: R2Shared
      - package: R2Streamer
      - package: R2Navigator
      - package: ReadiumOPDS
      - package: ReadiumLCP
      - package: Kingfisher
      - package: MBProgressHUD
      - package: SQLite
    settings:
      OTHER_SWIFT_FLAGS: -DLCP
```

It generates this project:

<img width="472" alt="Screenshot 2021-06-08 at 13 21 03" src="https://user-images.githubusercontent.com/58686775/121176334-614e4d00-c85c-11eb-84ff-93a463678142.png">
